#Nexis Web Configuration
#Tue Mar 31 15:17:10 KST 2026
db.host=localhost
db.name=nexis
db.password=nexis
db.port=3306
db.type=MariaDB
db.user=nexis
installed=true
server.host=localhost
server.name=Nexis Server
server.port=9000
